add: bash-dlc
hitszlug/wiki pull request #53
Opened 2022-10-23 10:28 UTC by Origami404

增加了 Linux 101 第六讲的 Bash 补充包章节

2022-10-23 10:51 UTC, rewired-gh requested changes

2022-10-23 10:51 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +> The first word specifies the command to be executed, and is passed as argument zero. The remaining words are passed as arguments to the invoked command.
建议使用中文。

2022-10-23 10:51 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +```
表述不够清晰。

> Instruction unclear, mission failed.

2022-10-23 10:51 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +**重定向带顺序的!!! 由后往前执行!!!!** `2>&1 >f` 会先 `>f`, 然后才 `2>&1`, 四舍五入没用。得写 `>f 2>&1`
建议先描述 `2>&1 >f`、`>f 2>&1` 表达的是什么，否则意图不清。

2022-10-23 10:51 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +下面用 `n`, `nn` 代表数字 (文件描述符), `m` 代表数字或 `-`, `f` 代表文件名，`T` 代表任意文本，`[]` 中代表可选
此段应当上移。

2022-10-23 10:51 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +sop: separator_op, 分割不同 bash 指令用的操作符, 可以是 '&' 或 ';'
对 `&` 的描述不够准确。

2022-10-23 10:51 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +# Linux 101 第 6 讲：Bash 语法补充包
建议将完整的文档写入，因为阅读受众不只有听讲座者。

2022-10-23 10:51 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +- `[n]>>f`: 重定向输出，但是附加模式
「附加模式」建议使用更好的表达。

> The `>>` appends to a file or creates the file if it doesn't exist. The `>` overwrites the file if it exists or creates it if it doesn't exist.

应当表达为 `>>` 会将内容重定向并添加到文件的末尾（若文件不存在，则自动创建）

2022-10-23 10:51 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +- `[n]>[|]f`: 重定向输出 `n(=1)` 为文件 `f`, 有 `|` 时不覆盖文件
建议提及 `noclobber`。

2022-10-23 10:51 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +- `&>>f`: 重定向 `1`, `2`, 但是附加模式，`>>f 2>&1`
`1`、`2` 意义不明。

2022-10-23 10:51 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +
建议添加常用的 `/dev/null`。

2022-10-23 10:53 UTC, rewired-gh requested changes

2022-10-23 10:53 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +curl -o - http://example.com/script.sh | bash
建议换成：
```sh
curl -o - http://example.com/script.sh | sh
```

2022-10-23 10:53 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +bash <(curl -o - http://example.com/script.sh)
同上

2022-10-23 10:56 UTC, rewired-gh approved these changes
<img width="160" src="https://n.hopp.top/lgtm.svg" />

2022-10-23 10:59 UTC, rewired-gh requested changes
idk, GitHub sucks

2022-10-25 14:28 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +- `&>>f`: 重定向 `1`, `2`, 但是附加模式，`>>f 2>&1`
我认为在此专注于描述文件重定向的上下文中, `0`, `1`, `2` 作为文件标识符分别代表标准输入, 标准输出和标准错误应当是不言自明的

2022-10-25 14:28 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +- `[n]>[|]f`: 重定向输出 `n(=1)` 为文件 `f`, 有 `|` 时不覆盖文件
确实, TODO + 1

2022-10-25 14:36 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +sop: separator_op, 分割不同 bash 指令用的操作符, 可以是 '&' 或 ';'
此处偏向语法描述, 我不认为需要在此赘述任何语法成分的作用. 并且 `&` 的作用在讲座中讲了.

2022-10-25 14:37 UTC, SoraShu commented on docs/popular-science/bash-dlc.md
> +# Linux 101 第 6 讲：Bash 语法补充包
至少不应该在此处使用这样的标题。应采用另一个标题，与 Linux 101 相关的提及放在标题下的引用块或者正文部分。不能假定所有受众是听讲座者。

2022-10-25 14:38 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +> The first word specifies the command to be executed, and is passed as argument zero. The remaining words are passed as arguments to the invoked command.
此处为引用 manual, 原文如此. 我将添加翻译, TODO + 1.

2022-10-25 14:39 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +```
我认为此种 EBNF + 扩展运算符的语法表示方法已足够清晰, 可否提供 "不够清晰" 的具体描述?

2022-10-25 14:41 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +# Linux 101 第 6 讲：Bash 语法补充包
阅读受众将假定为至少听过第六讲或具有同等水平的读者. 

我将修改标题为 "Bash 语法细节" (删去对讲座的指定), 并在原文开头引入提示与讲座链接. TODO+1

2022-10-25 14:41 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +
确实, TODO+1

2022-10-25 14:44 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +curl -o - http://example.com/script.sh | bash
鉴于本文章主题为 Bash, 并且该命令侧重点并非在说明 "用什么" 执行网上的脚本, 而是在说明 "执行网上脚本的原理" 上, 我认为此处使用 bash 是合理的.

2022-10-25 14:45 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +**重定向带顺序的!!! 由后往前执行!!!!** `2>&1 >f` 会先 `>f`, 然后才 `2>&1`, 四舍五入没用。得写 `>f 2>&1`
鉴于假定的受众水平, 我认为其不构成问题, 并且第六讲中有提及.

2022-10-25 14:47 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +下面用 `n`, `nn` 代表数字 (文件描述符), `m` 代表数字或 `-`, `f` 代表文件名，`T` 代表任意文本，`[]` 中代表可选
我认为保持原状能更好地保证此语法格式说明与下文列表的整体关系. 上一句的侧重点与下方整体不同. GNU Manual 上的描述顺序亦如原文.

2022-10-26 01:02 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +下面用 `n`, `nn` 代表数字 (文件描述符), `m` 代表数字或 `-`, `f` 代表文件名，`T` 代表任意文本，`[]` 中代表可选
第37行定义了f的含义，但是此前就使用了f，故应当上移。

2022-10-26 01:02 UTC, rewired-gh commented on docs/popular-science/bash-dlc.md
> +下面用 `n`, `nn` 代表数字 (文件描述符), `m` 代表数字或 `-`, `f` 代表文件名，`T` 代表任意文本，`[]` 中代表可选
第37行定义了f的含义，但是此前就使用了f，故应当上移。

2022-10-31 05:27 UTC, rewired-gh approved these changes
Timeout

2022-10-31 05:27 UTC, merged